[project]
name = "iflow-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=1.23.2",
    "requests>=2.32.5",
]

[project.scripts]
iflow-search = "main:main" 
